def stock(name_headers):
    data = {"filter": {"visibility": "ALL"}, "limit": 1000}
    r = requests.post("https://api-seller.ozon.ru/v3/product/info/stocks", headers=name_headers, json=data)
    print(r.status_code)
    stk1 = pd.json_normalize(r.json()['result']['items'], record_path=['stocks'], meta=["product_id", "offer_id"])
    total = pd.json_normalize(r.json()['result']).filter(items=['total'])
    total = np.array(total['total'][0])
    total = total.tolist()
    print(total)
    last_id = pd.json_normalize(r.json()['result']).filter(items=['last_id'])
    last_id = np.array(last_id['last_id'][0])
    last_id = last_id.tolist()
    print(last_id)
    data1 = {"filter": {"visibility": "ALL"}, 'last_id': last_id, "limit": 1000}
    r1 = requests.post(
        "https://api-seller.ozon.ru/v3/product/info/stocks", headers=name_headers, json=data1)
    # print(r1.content)
    dfs = pd.json_normalize(r1.json()['result']['items'], record_path=['stocks'], meta=["product_id", "offer_id"])
    total1 = pd.json_normalize(r1.json()['result']).filter(items=['total'])
    total1 = np.array(total1['total'][0])
    total1 = total1.tolist()
    print(total1)
    last_id1 = pd.json_normalize(r1.json()['result']).filter(items=['last_id'])
    last_id1 = np.array(last_id1['last_id'][0])
    last_id1 = last_id1.tolist()
    print(last_id1)
    # stk = pd.concat([stk1, dfs]).reset_index().drop(columns='index')
    # stk.to_excel('log/product.xlsx', columns=["product_id", "offer_id", 'type', 'present', 'reserved'])

    data2 = {"filter": {"visibility": "ALL"}, 'last_id': last_id, "limit": 1000}
    r2 = requests.post(
        "https://api-seller.ozon.ru/v3/product/info/stocks", headers=name_headers, json=data2)
    print(r2.content)
    dfs1 = pd.json_normalize(r2.json()['result']['items'], record_path=['stocks'], meta=["product_id", "offer_id"])
    total2 = pd.json_normalize(r2.json()['result']).filter(items=['total'])
    total2 = np.array(total2['total'][0])
    total2 = total2.tolist()
    print(total2)
    last_id2 = pd.json_normalize(r2.json()['result']).filter(items=['last_id'])
    last_id2 = np.array(last_id2['last_id'][0])
    last_id2 = last_id2.tolist()
    print(last_id2)
    stk = pd.concat([stk1, dfs, dfs1]).reset_index().drop(columns='index')
    stk.to_excel('log/product.xlsx', columns=["product_id", "offer_id", 'type', 'present', 'reserved'])
